### ISSUE TITLE
who decides "recommended groups"?

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#10]
in the Settings screen, when choosing Field groups, it mentions
"Recommended groups", but it's unclear who recommends that? (I assume
it's the DFID minimal set at the moment?)

**Comment by stevieflow** [comment]
I know these stars have been removed now - as it was causing confusion.

Could you check if this is still an issue therefore?

**Comment by rolfkleef** [comment]
ah ok, this can be closed then!

**Comment by stevieflow** [comment]
yay to closing issues!
