### ISSUE TITLE
zeros turning to blanks, and failing requirements

### ISSUE THREAD

**Issue by danmackenzie** [younginnovations/aidstream-old#101]
Hello,

I've been working with Restless Development, and going through their XML on the registry there a number of transactions that have no value i.e, no numerical value. This means they fail the DFID minimum requirements. 

I sent this to Restless who have checked the source data and stated that in each instance the cell containing the data is a '0', since there was no money moved that quarter. 

This means that AidStream is turning zeros into blanks, which causes the data to fail. Can we change it so '0' is a value?

Thanks

Daniel

**Comment by anjesh** [comment]
Hi Daniel,
That was apparently a bug, which has been resolved sometime back. If you go to those instances of transactions with blank value and change to 0, those will get saved. You will need to manually publish those activities to reflect in your xml files. Please let us know if you still have issues. I will close this issue for now. 
Best
Anjesh
