### ISSUE TITLE
Document URLs with special characters Not Saving

### ISSUE THREAD

**Issue by ChrisBrooks1987** [younginnovations/aidstream-old#103]
I have been working with a Publisher who is attempting to input a French language URL in to the Document-Link element in AidStream 1.03.
However, the accented 'é' e.g. in décembre is been rejected by AidStream which produces the following error message: Message: Please enter a single url in valid url format with valid characters (spaces are not allowed) e.g http(s)://mysite.com/filename.pdf. When I have replaced the é with a e in the URL it is accepted which suggests that the issue lies with this character. I have been able to replicate the fault in the Document-Links in both the Organisation and Activity Files.
Of note, the use of the accented é is accepted in the Title element and only appears to pose an issue in the URL.
When the Publisher completes the Document-Link page and attempts to save the data in addition to the issue outlined above it appears that the rest of the data that they inputted e.g. Language and Category Code have disappeared. Thus far I have not been able to replicate this issue in my own testing.
The attached image is a screenshot of the Document-Link page that shows the error message in the URL element. Of note, the Title element, containing école, is not flagged as invalid. 

![capture21](https://cloud.githubusercontent.com/assets/11769298/7316606/4613c572-ea70-11e4-8ade-9b0cd0e33f31.PNG)

**Comment by anjesh** [comment]
Fixed the url validation issue
