### ISSUE TITLE
Publisher Created Empty File On IATI Registry

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#107]
Hi Support, a publisher had a single activity in 'Draft' in their Aidstream account but they were still able to publish an empty file to the IATI Registry. Should the validation be able to stop this happening?

**Comment by anjesh** [comment]
This won't happen in V201as there are mandatory fields.

**Comment by wendyrogers** [comment]
That's good although the activity in the live system did have all mandatory fields present. Will the validation still stop it being published even if the activity is complete?

**Comment by anjesh** [comment]
Duplicate of https://github.com/younginnovations/aidstream/issues/118. Any discussion with empty files to continue there.
