### ISSUE TITLE
DAC 3 Digit Sector codes?

### ISSUE THREAD

**Issue by danmackenzie** [younginnovations/aidstream-old#108]
It has been raised by Tim Barker at HelpAge International that AidStream does not allow for the input of the DAC 3 Digit codes. Is this something that will be changed in v2.01 or the old version?

He has found the the DAC 5 Digit does not work for mapping their work. Other NGOs have said similar things.

**Comment by anjesh** [comment]
Duplicate of https://github.com/younginnovations/aidstream/issues/76 
Closing this. Further discussion there.
