### ISSUE TITLE
Non-Admin unclear error messaging when organisation setting not filled 

### ISSUE THREAD

**Issue by Jaspermid** [younginnovations/aidstream-old#110]
When logging in as non-admin user (with all permission) and organisation is not filled in all menu links redirect back to the dashboard. Although there is an error message in the top of the menu it is not clear that this needs to be resolved before moving further.

**Comment by anjesh** [comment]
@Jaspermid can you see if there's still problem with this one? We have upgraded to IATI 2.01 and not sure if this still is pending.

**Comment by anjesh** [comment]
Closing. Please reopen if there's still any problem with this.
