### ISSUE TITLE
Form to add a sector confusing

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#112]
The form to add sector codes is confusing:

![2015-09-25_01](https://cloud.githubusercontent.com/assets/223935/10096347/10c7b1a6-6371-11e5-9653-e21bafb7e218.png)
1. The narrative field is not needed for most vocabularies (the [guidance document suggests](http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/sector/narrative/) to only use it for RO and RO2), but the mandatory Text\* field suggests something needs to be entered. Maybe it can be made to show only when RO or RO2 is selected as vocabulary?
2. "Remove this" and "Add more" are repeated at 3. "Remove this narrative" and "Add another narrative" would be clearer. Also: trying to remove a single narrative doesn't work.
3. Better labels would be "Remove this sector" and "Add another sector".

**Comment by rolfkleef** [comment]
As suggested by @SJ-bond in https://github.com/younginnovations/aidstream-v201-migration/issues/22 for another element: perhaps it makes sense to indent the narrative block in many of such forms (css in style-wep.css):

![2015-09-29_01](https://cloud.githubusercontent.com/assets/223935/10161815/f024ef34-66a6-11e5-8f99-0d19ca40653a.png)

(And relabeling may add clarity)

**Comment by anjesh** [comment]
We have slightly indented the inner forms to separate from the container wherever they are present. You will need to do hard-refresh to see the change. 

![image](https://cloud.githubusercontent.com/assets/120488/10275562/03becf4a-6b68-11e5-8ef2-b6f034fec67b.png)

**Comment by anjesh** [comment]
Please reopen if there's anything with this issue.
