### ISSUE TITLE
Hand in Hand - Participating Orgs grayed out - preventing publishing

### ISSUE THREAD

**Issue by SJ-bond** [younginnovations/aidstream-old#113]
Hand in Hand International have their participating organisations element grayed out even though they have entered the data. Also see image attached - when you click on Add New Data, it also doesn't allow you to add organisation role and type to the organisation (perhaps this is why it's grayed out)? They have been given a deadline to publish new data by 30 Sept or their grant gets stopped, so please prioritise looking at this. (We were able to republish their org file, so it's not an AidStream to Registry issue).

![hand in hand participating orgs](https://cloud.githubusercontent.com/assets/8158574/10102621/7403d35a-6397-11e5-92f7-bdc354aea334.png)

**Comment by SJ-bond** [comment]
Hello, I resolved this - the second 'add more' button is the one with the detail (org type etc) rather than the first. Once we'd added in the funding org, we were able to publish. The reason for the two add more buttons really isn't clear in AidStream - perhaps showing this form in a kind of folder structure with indents would be clearer?

**Comment by anjesh** [comment]
The boxes are slightly indented now, so it might help to some extent for now.

![image](https://cloud.githubusercontent.com/assets/120488/10300783/ce942852-6c1a-11e5-87c8-acbd92b6ded6.png)

**Comment by anjesh** [comment]
Please reopen if you find issues here.
