### ISSUE TITLE
Narrative boxes in transactions - please rename

### ISSUE THREAD

**Issue by SJ-bond** [younginnovations/aidstream-old#114]
We are running AidStream training today, and users are finding it confusing to understand which narrative box goes with which sub-element in the transaction element. So for example, where you have to add in the text that goes with the provider organisation in a transaction, it's not clear that narrative = provider name. Also, it would be useful to have text in the Help button to explain this.

**Comment by anjesh** [comment]
It's slightly tricky to change the label in the existing aidstream forms, as all the labels are generated automatically, following the IATI standard. Any change in the labels means it breaks the flow. 

We have slightly indented the boxed now as you may see below

![image](https://cloud.githubusercontent.com/assets/120488/10275624/91a833b4-6b68-11e5-9273-bca90e9144e6.png)

As for the help text, the recent updates breaks the previous labels. We are preparing the list of the help links and admin can change the help text.

**Comment by anjesh** [comment]
Closing this. We have fixed the UI by slight indentation.
