### ISSUE TITLE
Transaction upload CSVs do not contain 2.01 fields

### ISSUE THREAD

**Issue by danmackenzie** [younginnovations/aidstream-old#116]
The CSV templates available for download from AidStream that orgs can use to upload transactions do not contain the new fields available for Transactions in v2.01.

I noticed that Recipient Country was missing as an option.

Cheers,

Daniel

**Comment by anjesh** [comment]
Correct. We haven't included those newly added fields in the upload for now. 
@iatisupport What do you say? Shall we add them?

**Comment by wendyrogers** [comment]
I guess for completeness we should add in the new fields to the upload template. However, if no users are currently using them then it might be better to use your resources to implement this in the 'new' version of Aidstream?

@danmackenzie & @rolfkleef - do you know if any of the users you are working with require this fix now?

**Comment by danmackenzie** [comment]
I don’t work with many publishers who use AidStream, and within that group I only know of one organisation that use the CSV upload - BRAC UK.

At the moment they will not be planning to use the extra fields. This is limited experience, but I wouldn’t see this as a priority for now.

Daniel Mackenzie

**Comment by rolfkleef** [comment]
I don't know of anyone here planning to use the newly added fields soon, so not urgent for us.

**Comment by anjesh** [comment]
Currently the detailed CSV contains fields that have been deprecated. The followings are the existing CSV fields. Number of these fields (most text for the codelist) will be deprecated from the template and sector, country, region will be added.

![image](https://cloud.githubusercontent.com/assets/120488/11389771/cbc109e2-936b-11e5-9ffa-74cf0cc9a22c.png)

The new V2.01 CSV template to contain the following fields only (in the given order). Also xml_lang is excluded from the csv as it's confusing. There could be only one narrative field, e.g for title, description in this template. Further could be added from the form later. 

Activity_Identifier
Activity_Title
Transaction-ref
TransactionType-code
TransactionDate-iso_date
TransactionValue-currency
TransactionValue-value_date
TransactionValue-text
Description-text
ProviderOrg-ref
ProviderOrg-provider_activity_id
ProviderOrg-text
ReceiverOrg-ref
ReceiverOrg-receiver_activity_id
ReceiverOrg-text
DisbursementChannel-code
Sector-vocabulary
Sector-code
RecipientCountry-code
RecipientRegion-vocabulary
RecipientRegion-code
FlowType-code
FinanceType-code
AidType-code
TiedStatus-code

**Comment by anjesh** [comment]
The detail transaction upload template now accepts all the V201 field. Please verify.
