### ISSUE TITLE
Provider Activity ID and currency fields missing from 'Simple' CSV template for uploading transactions

### ISSUE THREAD

**Issue by SJ-bond** [younginnovations/aidstream-old#119]
We've had a report from one organisation that the 'Simple csv'

 template for uploading transactions to AidStream no longer includes the fields for provider activity ID and currency? I haven't used this so can't verify whether these fields used to exist in the template, but it's been changed. Any ideas?

(It's included in the 'Detailed' template but they don't want to use that one currently.

PS - couldn't attach it as GitHub doesn't allow CSV files ....

**Comment by anjesh** [comment]
I don't think we have included the provider-activity-id in the simple csv template and for simplicity, but currency could have been part of that - i don't remember why that was not being included. Template has not been changed since it's introduced.

**Comment by danmackenzie** [comment]
Ok cool. I’m wondering if it could/should be added to the simple template, as providing a provider-activity-id / receiver-activity-id is part of the DfID minimum requirements (where possible) and is key to getting organisation data to appear on DevTracker.

Thoughts?

Daniel Mackenzie

**Comment by anjesh** [comment]
The following fields are to be included in the simple template (adding provider-activity-id, receiver-activity-id and currency)

Internal Reference
Incoming Fund
Expenditure
Disbursement
Commitment
Transaction Date
Transaction Currency *
Description
Provider Org Name
Provider Org Reference
Provider Activity Id *
Receiver Org Name
Receiver Org Reference
Receiver Activity Id *

**Comment by anjesh** [comment]
Please verify, we added extra fields in the simple template as well.
