### ISSUE TITLE
Linked Data Default very unclear

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#12]
the most intimidating unclear field is the Linked Data Default:

"[...] This attribute is URI path upon which an activity identifier can
be appended to get a dereferenceable URI for any activity contained
within a file. Where a publisher declares using one of these properties
that authoritative linked data is accessible for an activity then
consuming applications that are generating Linked Data from an IATI XML
file should assert an owl:sameAs relationship to the relevant URI."

I'm not sure if AidStream users are the first ones to enrich IATI with such semantic web links, I'd remove it or hide it by default

**Comment by Bjwebb** [comment]
No IATI publishers are using any of the Linked Data attributes yet. Moreover, it's something that smaller publishers are much less likely to use than larger publishers. Definitely agree with hiding/removing it in aidstream.

**Comment by stevieflow** [comment]
+1

**Comment by mesaugat** [comment]
v1.2.4 - Linked Data Default field has now been hidden.
