### ISSUE TITLE
Participating organisations: details dissapearing/jumping to different fields when saved

### ISSUE THREAD

**Issue by FionaWaters** [younginnovations/aidstream-old#121]
user is reporting issues when trying to save their participating organisations (30+ orgs). Namely, that the names of the organisations seem to move or jump fields when user saves the page. Please see details in Zendesk ticket here: https://iati.zendesk.com/agent/tickets/3003

Thanks

**Comment by anjesh** [comment]
I can't access this ticket.

**Comment by wendyrogers** [comment]
No problem Anjesh I have now assigned the ticket to your Help Desk queue

**Comment by FionaWaters** [comment]
Thanks Wendy – and for your help Anjesh.

Best wishes,

Fiona Waters
Effectiveness and Transparency Assistant
fwaters@bond.org.ukmailto:fwaters@bond.org.uk
Direct Line +44 (0)20 7520 1042

Connect with me on MyBondhttp://my.bond.org.uk/: http://my.bond.org.uk/users/fiona-waters

Bond · Regent’s Wharf · 8 All Saints Street · London · N1 9RL · United Kingdom
+44 (0)20 7837 8344 · bond@bond.org.ukmailto:bond@bond.org.uk · www.bond.org.ukhttp://www.bond.org.uk/

**Comment by anjesh** [comment]
We have fixed this in aidstream.org. There seems to be a bug in the code, which behaves abnormally when the count reaches 30. Great catch :) Please verify.
