### ISSUE TITLE
issue with Re:Cap:ture requirement in signup page on Firefox

### ISSUE THREAD

**Issue by SJ-bond** [younginnovations/aidstream-old#122]
Just had a call from someone trying to sign up to AidStream using Firefox browser. The RE;Cap:ture thingy (that tells AidStream you are a real person) wasn't working in their browser. I asked them to try it in Chrome and then let us know if it's still not working as it could be a popup issue or something. She did say that she has sent an email to either aidstream support or support@iatistandard.org (wasn't clear) so please keep a lookout for that ticket.

**Comment by anjesh** [comment]
This was due to the https and recaptcha is using http and couldn't load the image. The bug is fixed.

![image](https://cloud.githubusercontent.com/assets/120488/11291596/38a52f12-8f6a-11e5-9997-74b472e914bd.png)
