### ISSUE TITLE
Contact info: newline in email address gives confusing error message

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#125]
In an activity, when adding an email address under contact info:

If you press enter after the email address before moving to the next field, you receive an error message on the email field that is very confusing and doesn't help in solving the problem:

![2015-11-23_01](https://cloud.githubusercontent.com/assets/223935/11349389/479ab324-922c-11e5-919b-537edc1d77d9.png)

Suggestions:
- make the input field a single line, as with telephone and website
- strip leading and trailing whitespace before validating and storing

**Comment by anjesh** [comment]
Changed to text-input from text-area and also stripped the white chars if any during saving. 

![image](https://cloud.githubusercontent.com/assets/120488/11708139/263725e0-9f34-11e5-914f-9e2e58e72e25.png)
