### ISSUE TITLE
Provide "leave page?" confirmation on unsaved data

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#126]
It is becoming a good practice to warn a user when navigating away from a form with information added to it (e.g. Facebook: "You haven't finished your post yet. Do you want to leave without finishing?" with "Stay on this page" and "Leave this page" as buttons)

Having witnessed someone loose hard work filling in a long form and then clicking another information element in the right hand column rather than "Save", I think it would be good to add this feature to AidStream as well.

Alternatively: Github actually seems to save your input, so returning to for instance the "New issue" page after clicking away will show your earlier input (but without any clue this is happening).

**Comment by anjesh** [comment]
Now the popup appears if there are unsaved changes in the form. 

![image](https://cloud.githubusercontent.com/assets/120488/11708158/5a9aebdc-9f34-11e5-90b7-ad63b6b93a13.png)

**Comment by rolfkleef** [comment]
thanks!
