### ISSUE TITLE
Swap "Policy marker" and "Importance" fields

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#127]
When adding an activity, in the "Policy Marker" form: I propose to swap the fields "Policy marker" and "Importance", which seems closer to how I see people fill in the form: first what, then weight.

**Comment by anjesh** [comment]
Good point. Swapped the fields.

![image](https://cloud.githubusercontent.com/assets/120488/11708172/776612c8-9f34-11e5-8383-f7c36bab6e6c.png)
