### ISSUE TITLE
In the results overview, the title is not shown

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#129]
When adding results to an activity, the titles of the results are not shown, making it hard to find the right one to edit:

![2015-11-23_03](https://cloud.githubusercontent.com/assets/223935/11350142/601008ce-9230-11e5-95d3-99989e3b3e64.png)

**Comment by kritika555** [comment]
result -> 
  ->title - one/must
      ->narrative-more
->Description-one/optional 
   ->narrative -more
->Indicator-more(atleast one)
   -> title -one/must
  ->description-one/optional
  ->baseline - one/optional
  ->period-multiple/optional
        -> period-start -one/must
        ->period-end -one/must 
        ->target-once/optional
        ->actual- once/optional

**Comment by anjesh** [comment]
Titles are now shown

![image](https://cloud.githubusercontent.com/assets/120488/11708195/cf1f6096-9f34-11e5-9db2-04fa44ae8bb5.png)
