### ISSUE TITLE
Start /End Dates Incorrectly Display in Internet Explorer

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#13]
When adding or amending start/end dates using Internet Explorer the pages do not render correctly

**Comment by anjesh** [comment]
Can you give some example? Perhaps a screenshot of the incorrectly rendered dates.

**Comment by wendyrogers** [comment]
Have emailed Sarah J to see if she can remember who was having a problem with this so we can check what version of IE they were using?

**Comment by wendyrogers** [comment]
Have contacted the user who we thought had this problem but was advised that they are not/no longer using Internet Explorer. Therefore I will close this issue and if we encounter the problem elsewhere I'll raise a new issue instead.
