### ISSUE TITLE
Make the arrows collapse form blocks

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#130]
In a form, there often are multiple blocks, with an arrow head next to the title (blue circles below). It would be good if the block actually collapses when clicking the arrow but that doesn't seem to work.

![2015-11-23_04](https://cloud.githubusercontent.com/assets/223935/11350263/f3e89908-9230-11e5-806c-4a25f73e24aa.png)

**Comment by kritika555** [comment]
result -> 
->title - one/must
        ---->narrative-more
->Description-one/optional 
        ---->narrative -more
->Indicator-more(atleast one)
     -----> title -one/must
     ------>description-one/optional
     ------>baseline - one/optional
     ------->period-multiple/optional
          ------------> period-start -one/must
          ------------>period-end -one/must 
          ------------->target-once/optional
          ------------->actual- once/optional

**Comment by anjesh** [comment]
Results UI is now changed (consistent with other forms) and doesn't have those arrows now.

**Comment by rolfkleef** [comment]
ok, that's one way to solve it ;-)
