### ISSUE TITLE
Aidstream Allowed Publication of Two Transactions Without Transaction Dates

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#134]
The activity file published by Aidstream (https://www.aidstream.org/files/xml/ablechildafrica-activities.xml) for AbleChildAfrica currently reports two errors via the IATI Validator. On investigation it appears that two transactions have been published that do not contain a now mandatory (at V2.01) transaction date. The transaction both have a reference of 'DFID GPAF Y2 Q4 CHILD TO' and are for 868.33. (and we will also need to check if they are in fact duplicates?)

However, please can you  investigate the Aidstream validation to see if an amendment is required? 
See also http://iatistandard.org/201/activity-standard/overview/transactions/ as transaction-date, value, value-date and transaction-type are now all mandatory?

**Comment by wendyrogers** [comment]
Similar error reported for
Partos - http://aidstream.org/files/xml/partos_nl-activities.xml

The same error is also reported for 

Africa Educational Trust - http://www.aidstream.org/files/xml/aet-activities.xml
Afrikids - http://www.aidstream.org/files/xml/afrikids-gh.xml
Concern Uk - http://aidstream.org/files/xml/concernuk-pk.xml
Cord - http://www.aidstream.org/files/xml/cord-bi.xml
Emmanuel International UK -  http://www.aidstream.org/files/xml/eiuk-tz.xml
Food for the Hungry - http://www.aidstream.org/files/xml/fh-activities.xml
Find Your Feet -  http://www.aidstream.org/files/xml/fyf-in.xml & http://www.aidstream.org/files/xml/fyf-zw.xml
Hospice Africa - http://www.aidstream.org/files/xml/hauk-activities.xml
Homeless Int - http://www.aidstream.org/files/xml/hi-ao.xml & http://www.aidstream.org/files/xml/hi-lk.xml
Health Poverty Action - http://www.aidstream.org/files/xml/hpa-so.xml
Integrity Action - http://www.aidstream.org/files/xml/integrity_action-activities.xml
Open University - http://www.aidstream.org/files/xml/open_university-sl.xml
Railway Children - http://www.aidstream.org/public/files/xml/rc-activities.xml (& 1 other error)
Send a cow - http://www.aidstream.org/public/files/xml/sendacow-ug.xml
Signal -  http://aidstream.org/files/xml/signal-activities.xml
TargetTB - http://aidstream.org/files/xml/targettb-activities.xml
Twin - http://aidstream.org/files/xml/twin-iati-mw.xml
Ycare - http://www.aidstream.org/files/xml/ycare-activities.xml

**Comment by anjesh** [comment]
Same as https://github.com/younginnovations/aidstream/issues/135#issuecomment-167989277
