### ISSUE TITLE
Validation Error For Document Format in Aidstream

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#136]
The file generated by Aidstream for Acord currently does not validate - https://www.aidstream.org/files/xml/acord-cd.xml

The validator is reporting that the format attribute is missing from a document link: 

document-link url="http://www.acordinternational.org/our-work/where/drc/">

Therefore please can you investigate if the Aidstream validation needs amending as the format attribute is mandatory - http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/document-link/?

In addition same error in Organisation file
PIDG - http://www.aidstream.org/files/xml/pidg-org.xml

**Comment by wendyrogers** [comment]
Similar (but slightly different) document link validation errors also reported for
Camfed - http://www.aidstream.org/files/xml/camfed-gh.xml
Islamic Relief - http://aidstream.org/files/xml/irw-activities.xml
Learning for Life - http://www.aidstream.org/files/xml/learningforlife-np.xml (& 1 other error)
Opportunity International - http://www.aidstream.org/files/xml/opportunity-international-uk-ug.xml (& 1 other error)
Sense Int - http://www.aidstream.org/public/files/xml/sense_international-in.xml

Same error reported for
Cuamm Trustees - http://www.aidstream.org/files/xml/cuammtrustees-activities.xml
Samaritans Purse - http://www.aidstream.org/files/xml/spuk-activities.xml
Haiti Hospital Appeal - http://www.aidstream.org/files/xml/hha-activities.xml
Healthprom - http://www.aidstream.org/files/xml/hp_12-activities.xml
Health Poverty Action - http://www.aidstream.org/files/xml/hpa-pe.xml
Leonard Cheshire - http://www.aidstream.org/files/xml/lcd_admin-activities.xml (& 1 other error)
Tearfund - http://www.aidstream.org/files/xml/tearfund-activities.xml
Woman Kind World - http://aidstream.org/files/xml/womankindworld-activities.xml

**Comment by anjesh** [comment]
Again same problem as https://github.com/younginnovations/aidstream/issues/135#issuecomment-167989277 

AidStream form catches this problem if the data is being entered and edited without format attribute.
