### ISSUE TITLE
Validation Error For Transaction Amount Fields

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#137]
The activity file published by Aidstream (https://aidstream.org/files/xml/bracintl-activities.xml) for BRAC International currently reports (amongst other errors)  via the IATI Validator that 'Element 'value': '' is not a valid value of the atomic type 'xs:decimal'.'

On investigation it looks like the value amounts for transactions have been entered using commas and this might be causing the problem? Please can you investigate and amend the validation in Aidstream if required

**Comment by wendyrogers** [comment]
Similar error reported for

Restless - 
http://www.aidstream.org/public/files/xml/restless-in.xml
http://www.aidstream.org/files/xml/restless-ug.xml
http://www.aidstream.org/files/xml/restless-zm.xml
http://www.aidstream.org/files/xml/restless-zw.xml

**Comment by anjesh** [comment]
Same as https://github.com/younginnovations/aidstream/issues/135#issuecomment-167989277

These activities will need to be republished once we implement https://github.com/younginnovations/aidstream/issues/148
