### ISSUE TITLE
Validation Error Activity Date Missing Date

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#138]
The file produced by Aidstream for Child Hope UK - https://www.aidstream.org/files/xml/childhopeuk-et.xml is currently reporting an error via the IATI Validator 

Element 'activity-date': The attribute 'iso-date' is required but missing

It appears that the actual date for activity-date is missing. Please can you investigate?

**Comment by anjesh** [comment]
Same as https://github.com/younginnovations/aidstream/issues/135#issuecomment-167989277
