### ISSUE TITLE
Validation Error On Region Missing Code

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#139]
The file produced by Aidstream for Charity Projects (Comic Relief) - https://www.aidstream.org/files/xml/cprojects-activities.xml is currently reporting an error via the IATI Validator

Element 'recipient-region': The attribute 'code' is required but missing.

Also region is being reported along with recipient-country but not with a percentage split. Please can you investigate?

**Comment by anjesh** [comment]
Same as https://github.com/younginnovations/aidstream/issues/135#issuecomment-167989277
