### ISSUE TITLE
Provide a Transaction Csv Upload / Download Function (HIGH PRIORITY)

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#14]
From zendesk ticket 1251. Currently the transaction upload and download functions via CSV use CSV files with different templates. Can the functions be aligned so that transactions details can be downloaded from one activity into a CSV file that can then be re-uploaded to a different activity. Also can the function include all transaction fields including Provider-Activity-ID & Receiver-Activity-ID

**Comment by anjesh** [comment]
Prepared a mockup of the transactions page. There will be two ways to upload the transactions - simple (as it is currently) and detailed. 
![transactions-v1 2 4](https://cloud.githubusercontent.com/assets/120488/2773578/ade9bf4a-ca9f-11e3-8c30-fb8db861f2dc.png)

**Comment by wendyrogers** [comment]
Just looking at this amendment I just thought i would check on the functionality it will provide. I need to download all the transactions from one specific activity and upload them onto another specific activity. Will I be able to do that with this function? Thanks in advance

**Comment by anjesh** [comment]
Sorry about the delayed reply. Currently you will be able to download transactions of all the activities at once, rather than individual activity. Once downloaded, you can filter/edit/delete the transactions by activity of your choice and upload to another specific activity. Hope this helps.

**Comment by mesaugat** [comment]
Transactions can now be uploaded with two templates: `Simple` and `Detailed`. The detailed template contains all the transaction fields. The first three fields (Activity_Identifier, Activity_Title, Default_currency) are ignored during uploading. This is done to make it consistent with transaction CSV downloaded via Download My Data.
