### ISSUE TITLE
Multiple Validation Errors For DAPP

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#140]
The activity file for DAPP http://www.aidstream.org/files/xml/dapp-activities.xml is currently failing validation with a number of errors

Element 'legacy-data', attribute 'iati-equivalent': 'DAPP Malawi' is not a valid value of the atomic type 'xs:NMTOKEN'.

Element 'result': Missing child element(s). Expected is ( title ).

Element 'point': Missing child element(s). Expected is ( pos ).

Please can you investigate and amend Aidstream if required.

The other error reported by the validator is similar to that reported via issue #137

Element 'value': '42,166.72' is not a valid value of the atomic type 'xs:decimal'.

**Comment by anjesh** [comment]
Same as https://github.com/younginnovations/aidstream/issues/135#issuecomment-167989277
