### ISSUE TITLE
Validation Errors For Policy Marker Significance & Code are Missing

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#141]
The file produced by Aidstream for DECC - https://aidstream.org/files/xml/deccadmin-activities.xml - is currently reporting the following validation error

Element 'policy-marker': The attribute 'significance' is required but missing. 

for

<policy-marker vocabulary="1" code="6"/>

(NB other reported errors have already had other issues raised for them)

Please can you therefore investigate and amend Aidstream if required

**Comment by wendyrogers** [comment]
Also Policy Marker validation error for Sympany+

http://www.aidstream.org/files/xml/simone_sympany-activities.xml
http://www.aidstream.org/files/xml/simone_sympany-activities.xml
Element 'policy-marker': The attribute 'code' is required but missing.

**Comment by anjesh** [comment]
Same as https://github.com/younginnovations/aidstream/issues/135#issuecomment-167989277
