### ISSUE TITLE
Validation Error On Coordinates

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#143]
The file produced by Aidstream for Habitat for Humanity Great Britain  - http://www.aidstream.org/files/xml/hfhgb-br.xml is currently reporting an error via the IATI Validator

Element 'coordinates', attribute 'latitude': '-08° 03' 14''' is not a valid value of the atomic type 'xs:decimal'.

Please can you investigate and amend Aidstream as/if required

**Comment by anjesh** [comment]
same as https://github.com/younginnovations/aidstream/issues/135#issuecomment-167989277 

This wouldn't happen for new activities. Also would be taken for existing once https://github.com/younginnovations/aidstream/issues/148 is implemented.
