### ISSUE TITLE
Validation Error For Results

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#144]
The file produced by Aidstream for Heifer South Africa - http://www.aidstream.org/files/xml/hsa-za.xml - is currently failing on the IATI validator with two errors on results

Element 'result': The attribute 'type' is required but missing.
Element 'indicator': The attribute 'measure' is required but missing.

Please can you investigate and amend Aidstream if/as required

**Comment by wendyrogers** [comment]
Also results errors reported by validator for NGO Federation of Nepal - http://aidstream.org/files/xml/nfn-np.xml

Element 'indicator', attribute 'ascending': 'True' is not a valid value of the atomic type 'xs:boolean'.

And also for Pontis - 

https://www.aidstream.org/files/xml/pontis-by.xml
http://www.aidstream.org/files/xml/pontis-md.xml
http://www.aidstream.org/files/xml/pontis-sk.xml
http://www.aidstream.org/files/xml/pontis-tn.xml
Element 'description': This element is not expected. Expected is ( title ).

http://www.aidstream.org/files/xml/pontis-ke.xml
Element 'actual': This element is not expected. Expected is ( ##other\* ).

**Comment by anjesh** [comment]
Same as https://github.com/younginnovations/aidstream/issues/135#issuecomment-167989277
