### ISSUE TITLE
Validation Error For Budget

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#145]
The file produced by Aidstream for Living Earth - http://www.aidstream.org/public/files/xml/livingearth12-activities.xml - is currently failing on the IATI validator with an error for the Budget element (& 1 other error already reported - Sector)

Element 'budget': Missing child element(s). Expected is ( period-start ).

Please can you investigate and amend Aidstream if/as required

**Comment by wendyrogers** [comment]
Similar error for 

Rahnuma - http://aidstream.org/files/xml/rfpap-activities.xml (& other errors)
Street Child - http://www.aidstream.org/files/xml/street_child-activities.xml (& other errors)
Troc - http://www.aidstream.org/files/xml/troc-activities.xml

**Comment by anjesh** [comment]
Same as https://github.com/younginnovations/aidstream/issues/135#issuecomment-167989277
