### ISSUE TITLE
Validation Errors In Organisation File Budget Line

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#146]
The organisation file produced by Aidstream for Options Consultancy Services - http://aidstream.org/files/xml/options-org.xml - is currently failing on the IATI validator with an error for the Budget element 

Element 'budget-line': Missing child element(s). Expected is ( narrative ).

Please can you investigate and amend Aidstream if/as required

**Comment by wendyrogers** [comment]
Also same error in 

http://www.aidstream.org/files/xml/palladium-org.xml

**Comment by anjesh** [comment]
Same as https://github.com/younginnovations/aidstream/issues/135#issuecomment-167989277
