### ISSUE TITLE
Function: grouping organisations / admin

### ISSUE THREAD

**Issue by stevieflow** [younginnovations/aidstream-old#15]
Possible functions for publishers to be added to a list/group - via which designated admin users can then login and provide support 

This would work well - and could be tested - with organisations such as Bond and Partos

**Comment by mesaugat** [comment]
This feature is now included on latest update(v1.2.5). Publishers can be added to a designated group and managed accordingly.

**Comment by stevieflow** [comment]
Thanks

Can you explain more about which user level can make these groupings?

**Comment by mesaugat** [comment]
Superadmin users can create/manage organisation groups.
