### ISSUE TITLE
version-2.02: Non-specific error on publishing file in test account

### ISSUE THREAD

**Issue by rorads** [younginnovations/aidstream-old#155]
Using the test account: `61     Bill Steve Test`

After trying to take this activity from 'Draft' to 'Completed' (having converted it to 2.02):

![screen shot 2016-03-14 at 10 12 16](https://cloud.githubusercontent.com/assets/7805169/13741287/60d018d6-e9cd-11e5-8498-47717427f637.png)

I got this error:

![screen shot 2016-03-14 at 10 10 50](https://cloud.githubusercontent.com/assets/7805169/13741224/1002cad4-e9cd-11e5-891b-f05a99d773bd.png)

**Comment by imlunek** [comment]
This issue has been fixed.
