### ISSUE TITLE
Interface: Identifiers - seperate section

### ISSUE THREAD

**Issue by stevieflow** [younginnovations/aidstream-old#16]
Isolate the identifiers into one screen -

**Comment by anjesh** [comment]
Comments?
We are planning to change the instructions to simplify the process. The account identifier term is replaced with publisher identifier to make it consistent with Registry and to avoid confusion.
![registration](https://cloud.githubusercontent.com/assets/120488/3451775/d729f16c-01a0-11e4-9e9f-c1c23b541c00.png)
Now the user will be able to see and update the publisher identifier in the user profile page
![myaccount](https://cloud.githubusercontent.com/assets/120488/3451778/e0e774b8-01a0-11e4-95a9-37833b7c7542.png)
![change username](https://cloud.githubusercontent.com/assets/120488/3451780/e937bbf0-01a0-11e4-9161-04ae4d1eed35.png)
Also a bit of help text in Registry settings would also be helpful here. 
![setting](https://cloud.githubusercontent.com/assets/120488/3451781/ebdbbf1e-01a0-11e4-9740-9ccdc4bbc2d1.png)

**Comment by rolfkleef** [comment]
hi Anjesh, I would suggest changing the wording a little:
- use "organisation IATI identifier" only for the IATI org identifier
- use "organisation account name" (or something like that) for the AidStream/IATI Registry "identifier"

I think it will make the account name(s) part less "scary", and more obvious what their purpose is. People are used to account names (how you're known on the system) and profiles (how you're presented to others).

(A similar change of language would be good to do at the IATI Registry.)

**Comment by anjesh** [comment]
Hi Rolf,
We just thought of making the labels consistent with the Registry to avoid confusions. Your suggestions sound good but lets see what others have to say on this - to make similar changes in the Registry.

**Comment by rolfkleef** [comment]
Ok!

**Comment by stevieflow** [comment]
Hi

Yes - could be useful to make such simplifications/changes on the Registry also.  

@anjesh on the last screen there is a field for "reporting organisation identifier" - I'd assume that that would also be the same "Publisher Identifier" on the first screen?

**Comment by anjesh** [comment]
@stevieflow no - reporting org identifier in the last screen is IATI element and will appear in xml `<reporting-org .. >`

**Comment by stevieflow** [comment]
Hi @anjesh - understood, but I think that might be part of the issue! 
So
- first screen / registration
  Im not sure that asking for the Publishing Identifier is a  useful step, as people may not know a) what it is b) get it wrong c) not need it (they might not be ready to publish).  Therefore, I would remove that from the registration page.  Is there a reason to collect this at this stage?
- org / reporting-org
  I'd assume that the organisation using AidStream will _also_ be the reporting-org (I cant think of an exception).  Therefore, I'd suggest that reporting-org and "organisation details" are one and the same in terms of administration/description/access.  Within this, we would need careful consideration as to how to construct the identifier.  Suggestion: Perhaps if they state which country they are based in , then the relevant country code can be added as the first part of their identifier?
- IATI Registry Info
  It is right to isolate these accordingly, and not confuse with the Org identifiers.  Hence, I would remove reference to this from the registration page, etc - this is info that is used _only_ to connect to the Registry.
  (there is an argument that the Registry ID and Org ID should be the same)
- usernames 
  As @rolfkleef suggests, we should simplify the language / labels used for usernames - as people know what these mean

Hope this is helpful in some way - appreciate it isnt the whole answer!

**Comment by wendyrogers** [comment]
I would just also add if it is possible to only ask for the publisher ID and API key when the publisher is at the point when they are ready to publish? We quite often find that publishers create a registry account to get this information and then it is a very long time (and sometimes not at all) before they do actually publish.

Although this is less of a problem now as we have amended the displayed list of publishers on the Registry to only show those that have datafiles present we are still sometimes left with obsolete or unused Registry accounts.

(We have talked in the past about Aidstream using the API to create the Registry account on behalf of the user but I suspect that such a change is too big here given all the other information required on the Registry)

**Comment by anjesh** [comment]
Publisher identifier in the first step is to identify it with their usernames. Our initial design was that username should be the concat of account name (which is confusing at first and its similar to that of publisher id - basically abbr of the org) and the name of the user who will be using the system (admin during registration process and can create other users later on). All the users within that org will share the same prefix (publisher-id or account-name or org abbr). This got me thinking maybe we just ask for the organisation name and then the abbreviation of the organisation, which will be part of the username - totally avoiding publisher id until one goes to registry section in the settings. 

I like @stevieflow idea on asking for the country, perhaps we can also ask for the registration-agency and organisation number separately and then provide with the reporting-org-identifier. Will capture that in mockups.

**Comment by stevieflow** [comment]
Hi @anjesh 

Thanks for thinking on this

One thing you might want to check from a UI / code point of view would be this tool that @timdavies made (prior to the TAG at Montreal): http://practicalparticipation.github.io/organisation-id-tool/ - this might be how you could take users through minting their org ID.

NB - we should consider that the list on IATI - http://iatistandard.org/codelists/OrganisationRegistrationAgency/ - is not comprehensive / worldwide, so we might not want to force users through this route entirely.  It should be possible to follow the process but manually enter details , perhaps

Thanks

Steven

**Comment by anjesh** [comment]
Will do minor change in the registration page for now. Will later do multi-step registration process for more clarity. 
![registration](https://cloud.githubusercontent.com/assets/120488/4022935/34dc416c-2b67-11e4-988d-06a473a4733a.png)

**Comment by mesaugat** [comment]
The registration form has been changed as per the mock-up listed above. The label 'Account Identifier' has been replaced by 'Organisation User Identifier' to avoid confusion.

The description text has also been updated.
