### ISSUE TITLE
Location Map Has Place Names in Multiple Languages

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#19]
When adding location details using the map, place names were displayed in multiple languages eg english, chinese etc.

**Comment by stevieflow** [comment]
Putting into 1.04 milestone , due to `location` changes

**Comment by anjesh** [comment]
The multiple language in map is due to the default behaviour of OSM. Looks like https://gist.github.com/mourner/1804938 from http://stackoverflow.com/questions/18589621/setting-map-language-to-english-in-openstreetmap-with-leafletjs looks useful.

**Comment by mesaugat** [comment]
This is the default behavior of OSM. Trying different map tile providers didn't work. We may have to rethink on this.

**Comment by mesaugat** [comment]
The map now uses Mapbox tiles with English labels. However, the locations will still be fetched in multiple languages as it is the default behavior of OSM reverse geocoding.
