### ISSUE TITLE
Pop up during publishing stages

### ISSUE THREAD

**Issue by stevieflow** [younginnovations/aidstream-old#20]
I noticed that when you edit an activity, you still have to go through the Completed > Verified > Published stages - even though this pop-up appears:

"You have selected "Yes" in "Automatically Update the IATI Registry when publishing files" in Settings. Your files will be directly published to the IATI Registry."

I think this makes sense, but we probably want to make it much clearer that once a file is edited, it needs to be republished? Or - should this be taking place?

**Comment by stevieflow** [comment]
Similar too, but different from: https://github.com/younginnovations/aidstream/issues/8

**Comment by mesaugat** [comment]
The pop up during different stages can now be disabled by clicking on 'Okay, Got It'. This will disable the popup from appearing next time. However, if the user doesn't click on it the popup will reappear next time.
![selection_001](https://cloud.githubusercontent.com/assets/4240991/3090433/2eb41dee-e58c-11e3-9720-99379dc819cf.png)

The popup will also stop appearing if any one of the activities is in published state or is published.

**Comment by mesaugat** [comment]
This fixes #8
