### ISSUE TITLE
Backwards compatibility with IATI versions

### ISSUE THREAD

**Issue by stevieflow** [younginnovations/aidstream-old#21]
Particularly with the advent of 2.01, it will become pressing to thinking about backwards compatibility. 

How would I opt-out of 2.01, for example?

**Comment by rolfkleef** [comment]
Even with 1.03 > 1.04: I guess as a user I'd want to see a message "IATI version 1.04 is out, do you want to start publishing in this new version?"; with possibly some help in migrating fields where needed.

Without checking the details now, I can imagine that eg. location data could be published either as 1.03 or as 1.04 (gazetteer -> location-id/@vocabulary), but I might have visualisation tools that currently work with the 1.03 version of my data.

(And that then adds the question: how long do you want to keep supporting earlier versions within AidStream...)

**Comment by stevieflow** [comment]
Thanks Rolf

It's an important issue to consider, particularly with the advent of 2.01 next year, but also (as you state) with different `location` for 1.04

Hence, we might want to also delay 1.04 (https://github.com/younginnovations/aidstream/issues/17) integration in light of this

**Comment by anjesh** [comment]
Will be taken care in new AidStream https://github.com/younginnovations/aidstream-new/issues/3
