### ISSUE TITLE
xml index page

### ISSUE THREAD

**Issue by stevieflow** [younginnovations/aidstream-old#25]
@anjesh could you also include the Registry ID in this XML file?

**Comment by anjesh** [comment]
Lets add registry-publisher-id and make minor change in the xml as follows

``` xml
<iati-publisher>
<name>ACORD</name>
<publisher-id>reg-pub-id</publisher-id>
<iati-files>
<iati-activity>http://aidstream.org/public/files/xml/acord-cd.xml</iati-activity>
<iati-activity>http://aidstream.org/public/files/xml/acord-tz.xml</iati-activity>
<iati-organisation>http://aidstream.org/public/files/xml/acord-org.xml</iati-organisation>
</iati-files>
</iati-publisher>
```

**Comment by Bjwebb** [comment]
Could the XML element actually be `registry-publisher-id` to distinguish it from the reporting-org/@ref (e.g. GB-1) which CKAN records and refers to as the `publisher_iati_id`.

**Comment by mesaugat** [comment]
Yes the XML element has been set to `registry-publisher-id` as per v1.2.3
