### ISSUE TITLE
No mention that the source code is available on Aidstream

### ISSUE THREAD

**Issue by caprenter** [younginnovations/aidstream-old#28]
There doesn't seem to be a link to the issue list of mention of the source code on the main Aidstream site.

This may also be linked to the licencing of the code:
https://github.com/younginnovations/aidstream/issues/26

**Comment by stevieflow** [comment]
Also - reference to which is the latest build in release  -and a link to the milestone, perhaps

**Comment by mesaugat** [comment]
"Fork us on GitHub" now mentioned on AidStream homepage.
