### ISSUE TITLE
uploading transactions: s.n.

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#29]
In the transactions CSV template, there is a column "internal reference". In the list in AidStream, there is a column "S.N.".

When adding transactions with internal reference 1, 2, ... they will be presented in the list in reverse order, so the numbers become confusing.

I'd suggest removing the "S.N." as these have no meaning to the end user, and perhaps adding an "internal reference" column.

**Comment by mesaugat** [comment]
Yes, the `S.N.` column has been replaced by the `Internal Ref` column with the latest update.
