### ISSUE TITLE
Check for duplications in the transactions CSV file upload

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream-old#3]
Currently every new CSV upload will create new transactions. The transactions should be checked for duplication using internal-ref-number and update the transactions if already present.

**Comment by mesaugat** [comment]
Transactions now are updated using the internal-ref-number. Otherwise, new transactions are created. Updated on v1.2.3

**Comment by anjesh** [comment]
If internal-ref-number is missing, then it will assume those rows as new transactions. There are instances where different transactions have same internal-ref-number in the system, in those case the bulk upload will give error message. The aidstream validation doesn't check for the uniqueness of internal-ref-number for the given organisation, but looks like we might need to think about that to aid bulk transactions upload and update.
