### ISSUE TITLE
Drop down vocabulary list in Policy marker does not work

### ISSUE THREAD

**Issue by Jaspermid** [younginnovations/aidstream-old#31]
Selecting different vocabularies within the policy marker field does not seem to change the options available as a policy marker. The IATI standard website also doesn't mention different type of codelists, the 8 options seem to be a given.

**Comment by stevieflow** [comment]
This will be a known issue - as Policy Marker is _just_ DAC - 

@bill-anderson is there a design reason for declaring a different Policy Marker vocabulary?

As the AidStream interface level, I can see that selecting a different vocabulary for any relevant element could cause problems - as we have no real lookup.  One to review going forward - perhaps this can be mitigated in AidStream through some on-screen help tips

Thanks for raising this @Jaspermid

**Comment by bill-anderson** [comment]
For clarity what we currently have should in fact be called CRS Policy Marker. The eight values in the codelist are each separate columns in the CRS++ reporting template. We normalised this. So while we own this list it is dependent on the CRS.

Theoretically we could add other values to the list, but firstly I think this would be confusing and secondly I'm not aware of any other system of similar markers in widespread use.

**Comment by stevieflow** [comment]
Action from call 14 May : remove vocabulary drop down in the interface
