### ISSUE TITLE
Duplicate a single activity

### ISSUE THREAD

**Issue by siemvaessen** [younginnovations/aidstream-old#32]
It would save the user time when an activity can be cloned. Many activities may be in the same sector, country etc. The option 'duplicate' next to 'view' & 'delete' which would create a new item with an addition in the title 'duplicate' would suffice.

**Comment by mesaugat** [comment]
Duplicating an activity is now possible with current update (v1.2.6). However, the transactions are not duplicated, it has to be inserted/uploaded manually to the duplicated activity.
