### ISSUE TITLE
Lack of proper unicode support

### ISSUE THREAD

**Issue by Bjwebb** [younginnovations/aidstream-old#33]
The page is declared as UTF-8, but I suspect the database might actually be using Windows-1252, since I can add characters not in ascii (but in Windows-1252), like é just fine. However, if I try to add some other characters, I get returned question marks when I save it. E.g. αβγ becomes ???

**Comment by Bjwebb** [comment]
Actually, double checking this, it looks like the database might be using Windows-1252, I've updated my description accordingly.

**Comment by mesaugat** [comment]
The database was using the default `latin1_swedish_ci` collation. It has now been changed to `utf8_unicode_ci`. Thus, the database now supports all unicode characters.
