### ISSUE TITLE
Multiple transactions delete option 

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream-old#35]
Use of checkboxes in the transactions listing so that multiple transactions could be deleted at once. Suggested by Tim from HelpAge International.

**Comment by mesaugat** [comment]
Deletion of multiple transactions is now possible. (v1.2.7)
![selection_001](https://cloud.githubusercontent.com/assets/4240991/3370814/30acff7e-fb96-11e3-97b2-4db0fdc25a22.png)
