### ISSUE TITLE
Use of Popups on Internet Explorer

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#36]
We have had a few publishers who have had problems with Aidstream because their organisation's systems do not allow the use of popup windows. The most recent case is as per Zendesk ticket #1380 where a publisher was unable to publish a file due to the use of a popup window. As a result is there an alternative mechanism that Aidstream could use to prevent such incidents?

**Comment by wendyrogers** [comment]
I have gone back to the publisher to ask if they are also unable to enable Javascript popups on their organisation system (see Zendesk ticket #1419)

**Comment by wendyrogers** [comment]
One of the publishers who encountered this problem are using Internet Explorer 9 (v. 9.0.8112) and their system is configured centrally as follows:

Use pop-up blocker --> enable 
Scripting of Java applets --> prompt

When using Aidstream they were unable to see the popup window that asks the Publisher if they want to go ahead and publish

**Comment by SJ-bond** [comment]
Hello, I recently had two examples of this, both using IE 9. Users were unable to see the "Are you sure you want to go ahead and publish" popup window in IE9. They switched browsers (one to Firefox and one to Chrome) and were able to publish.

**Comment by wendyrogers** [comment]
I have also just had another instance of this (se Zendesk ticket #1223) The publisher was using  Internet Explorer 11 and said that scripting hasn't been disabled and it seems to make no difference whether pop ups are enabled or not?

Looks like IE could be the common link here?

**Comment by mesaugat** [comment]
Javascript issue with Internet Explorer. Should work fine now with v1.2.8 update.
