### ISSUE TITLE
Always Display Transactions In Date Order (Earliest First)

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#39]
Sometimes transactions may be added to an activity out of date order ( eg as a result or importing transactions from other activities - see transactions on activity 1 for International Planned Parenthood Federation). Therefore when viewing or editing please could transactions always be displayed in date order (earliest date first)

**Comment by wendyrogers** [comment]
Here is an example of an activity with transactions not listed in transaction date order http://www.aidstream.org/activity/view-activity-info/?activity_id=1092
![trans_date_order](https://cloud.githubusercontent.com/assets/5500787/3172675/cde337c2-ebd8-11e3-904d-4c6fea9352cf.gif)

**Comment by anjesh** [comment]
Oh. i was looking at transactions list page when you click on the transaction menu. Got your point.

**Comment by mesaugat** [comment]
Transactions are now sorted as per earliest date.
