### ISSUE TITLE
twitter updates

### ISSUE THREAD

**Issue by stevieflow** [younginnovations/aidstream-old#40]
The twitter updates seem to cover every update an organisation publishes - which can override the #IATI twitter hashtag.

Suggest to modify the tweets to:

[Org Name] has published their #IATIdata, using #AidStream. View the data here: URL...

**Comment by mesaugat** [comment]
The tweet has been modified with the current update(v1.2.5) to: 
`Org Name` has published their #IATIData. View the data here: `URL` #AidStream
