### ISSUE TITLE
DAC codelists for sector codes

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#41]
When adding a sector, it's possible to select DAC, but only with the 5-digit DAC-codes.

In 1.03, it is possible to use a 3-digit category code as well. In 1.04, this is even a separate code list.

Maybe the 3-digit list could be added?

...

Also, the 1.03 list of 5-digit DAC codes is incomplete compared to the 1.04 list. (For instance: 15153 is not on the 1.03 version.)

This should be addressed when moving to the 1.04 version (not sure if in the 1.03 version too).

**Comment by wendyrogers** [comment]
Hi @rolfkleef I think this issue has now been superceded by https://github.com/younginnovations/aidstream/issues/76?

Are you happy if this issue is closed now?

**Comment by rolfkleef** [comment]
ah yes, this is a duplicate!
