### ISSUE TITLE
Checkboxes in List Activities view not selectable

### ISSUE THREAD

**Issue by siemvaessen** [younginnovations/aidstream-old#43]
Upon modifying one of the activities on http://aidstream.org/wep/view-activities I want to push/publish it. Usually I was able to select the checkbox left of any of the activities and the push the blue Publish button.

I am now unable to select any of the checkboxes and perform that action. This happens to me in on my mac:
- Chrome (recent version)
- Safari (recent version)
- Firefox (recent version)

and as fallback also tried using Internet Explorer in a VM (Parallels Desktop) running Windows 8.1, with the most recent IE version which has the same issue. I am therefore unable to publish anything (!)

![screen shot 2014-06-13 at 18 59 50](https://cloud.githubusercontent.com/assets/961036/3272012/673d660e-f313-11e3-9484-03e1062ef2ff.png)

**Comment by mesaugat** [comment]
Only activities with `verified` state can be selected. If you have modified the activity it should be in `draft` state. You need to change the state of the activity to `verified` and then only you can select the activity to publish.

You cannot publish activities other than those in `verified` state.

**Comment by siemvaessen** [comment]
Ah yes, this is one of the reasons I should not be working on some stuff later Friday. Sorry!
