### ISSUE TITLE
After login, dynamic pages do not recognise sessions

### ISSUE THREAD

**Issue by berjan** [younginnovations/aidstream-old#46]
Hi,

We have a done a clean installation of Aidstream. We have followed the setup instructions. 

We are now able to create accounts. 

When an account is logging in, the navigation does not respond. A session has been created, but if we want to navigate to the dashboard or other parts, the site does not respond and is showing the login page. 

We have checked the database and user permissions, user groups are not created.

We are unable to find problems in the log files.

Is there a way that we can determine what the problem might be? Do you have any suggestions?

Thx,

**Comment by mesaugat** [comment]
This seems like a htaccess problem. Please make a copy of `.htaccess_bak` as `.htaccess` in the root folder and in the public folder.

For the .htaccess to work: Enable apache2 modules `headers`, `expires` and `cache`.

**Comment by berjan** [comment]
Hi, 

Thx for your reply. After enabling the modules headers, expires and cache modules, the dynamic pages still do not render :(

The headers are looking good and are sent through. Could it be an issue of the Zend framework configuration?

**Comment by mesaugat** [comment]
Which browser are you using ? And could you look at your apache error logs ?

**Comment by berjan** [comment]
We use Chrome browser, have tested it also in Safari and FireFox. 

Apache errors are empty. 

Latest log issue found in the data/log directory: 2014-07-01T12:28:07+02:00 ERR (3): Invalid controller specified (myaccount)

**Comment by mesaugat** [comment]
Have you setup an apache VirtualHost ?

**Comment by mesaugat** [comment]
Also ensure that apache modules `mod_rewrite` and `libphp5` are enabled. These modules should be enabled by default.

The root directory should also have `AllowOverride` set to `All`
Restart apache.

**Comment by berjan** [comment]
Yes,

like this:

<VirtualHost *:80>

   ServerName servername.com

   ServerAdmin berjan@company.com

   DocumentRoot /var/www/aidstream/public

   <Directory "/var/www/aidstream/public">

```
    DirectoryIndex index.php

    AllowOverride All

    Order allow,deny

    Allow from all
```

   </Directory>

</VirtualHost>

**Comment by mesaugat** [comment]
Remove `/public` from DocumentRoot and Directory. I am using this configuration:

< VirtualHost *:80>
ServerAdmin webmaster@localhost
ServerName dev.aidstream.org

DocumentRoot /var/www/aidstream

< Directory /var/www/aidstream>
Options Indexes FollowSymLinks
AllowOverride All
< /Directory>
< /VirtualHost>

If you are using Apache 2.4 include `Require all granted` inside your < Directory> tag.

**Comment by berjan** [comment]
We are using apache 2.4.

We have changed the virtualhost according to your last post. Sadly, no change in operation...

**Comment by mesaugat** [comment]
Remove any session instances inside of data/session folder and try logging in again.

**Comment by berjan** [comment]
Have done this. No success either....

**Comment by mesaugat** [comment]
It should be working by now. Seems pretty weird. Can you post the screenshot with the URL as well ?

**Comment by berjan** [comment]
E-mail is working, so you could also create an account. De link is aidstream.zimmermanzimmerman.com

**Comment by mesaugat** [comment]
This still looks like a htaccess problem. Looks like htaccess needs to be reconfigured on your server. I don't think anything else is causing this problem.

**Comment by carlio** [comment]
I don't think this is a .htaccess problem, as all requests work find and there are no errors or 404 in the Apache log. It seems like this line is simply returning 'false' for all users: https://github.com/younginnovations/aidstream/blob/master/library/App/AccessCheck.php#L22

In addition, the `user_group` and `user_permission` DB tables are empty.

**Comment by mesaugat** [comment]
The `user_group` and `user_permission` tables are supposed to be empty. Looks like you have an empty `role` table ?

**Comment by VincentVW** [comment]
Hi all, 

The problem was in the codelists.sql file, there's a comma missing on line 1111. 

(648, 'ZW', 'ZIMBABWE', 3),
(649, 'SS', 'SOUTH SUDAN', 1),
(650, 'AN', 'NETHERLAND ANTILLES', 1)  <--- here
(651, 'XK', 'KOSOVO', 1);

Causing a sql syntax error and all preceding tables left empty. Including the role table and a failing authentication etc... I just send a pull request to fix the codelists sql dump file.

Thanks for the help on this @mesaugat @carlio

**Comment by siemvaessen** [comment]
Excellent work @VincentVW !
