### ISSUE TITLE
When Specifying 'RO' for Sector Vocabulary Should Code or Text Field Be Used

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#47]
Emms International have recently published and have specified their own vocabulary via 'RO' for Sector codes. However, on their activity GB-OSCR-SC032327-MW I noticed that they had specified within Aidstream a value of 'Health' in the code field and had left the text field blank. However, the output XML did not include the specified code field value at all?
<sector code="" percentage="100" vocabulary="RO"/>

Therefore should the value of 'Health' have been output as the sector code in this case or should the sector code not have been available for the user to fill in so that they would have had to have specified 'health' in the text field?

**Comment by stevieflow** [comment]
@iatisupport @younginnovations/aidstream-team 

I took a look at this

I thought it might be that the publisher had used the string `Health` as the code, so I edited it to have a code of `H` and text as `Health`.

The resultant XML has

```
<sector code="" percentage="100" vocabulary="RO">Health</sector>
```

So - this doen't seem to work 

@younginnovations/aidstream-team can you clarify what the rules in Aidstream are, for RO on sector?  

Thanks

Steven

**Comment by mesaugat** [comment]
With the new update `v1.2.8`: Sector code will now appear in the resultant XML if anything is specified in the `Sector` field for any vocabulary.
