### ISSUE TITLE
Contact Info Type Values Should Be Constrained To Codelist

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#49]
At the moment a user can enter free text into the 'Type' field of Activity 'Contact Info'. However, I think the values allowed in this field should be constrained to those on the Contact Type codelist at http://iatistandard.org/codelists/ContactType/?

**Comment by anjesh** [comment]
Now contract type is codelist in IATI v201 upgrade

![image](https://cloud.githubusercontent.com/assets/120488/10975753/83ba4bb4-8410-11e5-83f4-849c1f2ef90f.png)

**Comment by anjesh** [comment]
Please reopen if you find issues here.
