### ISSUE TITLE
status "edit" looks like an edit button

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#5]
in the list of activties, the workflow state "edit" looks like a
button you want to click to edit that activity; the "view" link that
appears when hovering the title doesn't imply you can edit it too.

(I'd suggest making the status clickable; and: status "edit" might be renamed "draft" or "concept"?)

**Comment by anjesh** [comment]
Makes sense. Draft sounds good.

**Comment by mesaugat** [comment]
Status `Edit` is now renamed to `Draft`. However, the states are not clickable currently. We need to look into that.
