### ISSUE TITLE
Make New Users More Aware Of The Demo Facility

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#50]
We still get a number of users signing up for accounts on Aidstream that they are obviously using just to try the application out. Although this is not a big problem it does mean that we have quite a lot of accounts that end up not being used etc. As we have the demo facility that allows users to try Aidstream out without the need for signing up etc I was wondering if we could perhaps make this feature more prominent - perhaps by changing the wording on the 'Demo' button to 'Try It Out' or something similar?

**Comment by mesaugat** [comment]
`Try a Demo` button added to AidStream homepage so that users are more aware of the demo facility. (v1.2.9)
