### ISSUE TITLE
Classifications - Collaboration type - drop down and hover-over guidance different

### ISSUE THREAD

**Issue by ghost** [younginnovations/aidstream-old#53]
The drop down list for collaboration type contains 4 codes

> 1. \- Bilateral
>    2 - Multilateral
>    3 - Bilateral, core contributions to NGOs and other private bodies / PPPs
>    4 - Multilateral outflows

The Guidance next to it refers to 6:

> This is the code for the collaboration type. There are six of these: 1 - Bilateral, 2 - Multilateral, 4 - Multilateral outflows, 5 - Aid through NGOs, 6 - Aid to NGOs, 7 - Aid through PPPs.

The iatistandard codelist only contains 5 - http://iatistandard.org/codelists/CollaborationType/

**Comment by anjesh** [comment]
Thanks.  Will add and fix the help-text.
