### ISSUE TITLE
Create A Changelog Web Page

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#54]
Please could we set up a page on the Aidstream web site as a changelog that can record each release (with release date) and the changes that have been included? I know that we have Github but given that many of our users are not particularly technical it would be preferable to provide the information in a more simple and public facing way.  It would also be good to build up a history of the changes – so perhaps initially setting up the page to cover the changes made in the last 6 – 9 months so that if anyone can see what previous changes have been made by referring to the web page?

**Comment by rolfkleef** [comment]
Would be nice to post those release updates/changelogs on the blog as well, so rss junkies like myself get notified :-)

**Comment by wendyrogers** [comment]
Hi team, do you have a date for when this might be available? Thanks

**Comment by anjesh** [comment]
This change will be pushed on Aug 25 Monday.

**Comment by mesaugat** [comment]
AidStream changelog now available at http://aidstream.org/changelog
