### ISSUE TITLE
Unable to Publish Pakistan File 

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#55]
Raised from Zendesk ticket https://iati.zendesk.com/agent/#/tickets/1598. Please can you investigate why we are unable to publish the Pakistan file from Aidstream for this publisher? Thanks

**Comment by anjesh** [comment]
@stevieflow Can the dataset name be changed from concernuk-pk to something else concernuk-pk-1?  AidStream now gives the Name conflict error as it tries to create the dataset (concernuk-pk) that already exists.

**Comment by stevieflow** [comment]
Will do so - but will update via zendesk.
