### ISSUE TITLE
Publishing returns 409 error

### ISSUE THREAD

**Issue by VincentVW** [younginnovations/aidstream-old#57]
When trying to publish an IATI XML file to the registry we get a 409 error back from the registry. In the interface this shows as  'Conflict (e.g. name already exists)’. (On http://aidstream.zimmermanzimmerman.com ).

With debugging I found this is the actual error: ["Publisher name missing. Please select a publisher from the list.”]

Any idea on what might cause this or what I'm doing wrong? 

Note: we are not trying to push to the live registry,@stevieflow gave us the staging url for testing; http://iati2.staging.ckanhosted.com/api/ and I set that as the registry.url in the application.ini cfg. This all seems to work well.

**Comment by stevieflow** [comment]
@VincentVW I'm not convinced that you've created an actual publishing org - I sent this to @siemvaessen : 
http://discuss.iatistandard.org/t/testing-iati-regsitry-publishing/71/6

**Comment by VincentVW** [comment]
@stevieflow I used the publisher "testfoundation" that Adrian made and shows up in this call. 

http://iati2.staging.ckanhosted.com/api/action/organization_list

That's an approved publisher right?

**Comment by stevieflow** [comment]
@VincentVW thanks

Yes - that seems to be valid: http://iati2.staging.ckanhosted.com/publisher/testfoundation

Only @adriancollier is listed as an admin for this org though - I assume you are using his username/API key (I think @siemvaessen was talking about a different user?)?

**Comment by adriancollier** [comment]
Yes, @siemvaessen was using a different org and file - though with my (appearingly correct) details, I still get an error. On the UI it shows:
![screen shot 2014-08-01 at 9 50 27](https://cloud.githubusercontent.com/assets/1426234/3776171/a6691f0e-1950-11e4-9030-6eb43c712f98.png)

**Comment by stevieflow** [comment]
Just spoke to @adriancollier - who will try a new org - there may have been a clash with testfound and testfoundation

**Comment by adriancollier** [comment]
OK, so I've tried again, but I think I have done somethis wrong again. Here are my settings and the result:
![screen shot 2014-08-01 at 12 47 33](https://cloud.githubusercontent.com/assets/1426234/3777901/696ba568-1969-11e4-90f2-2287497538b8.png)
![screen shot 2014-08-01 at 12 47 22](https://cloud.githubusercontent.com/assets/1426234/3777902/6b955b9a-1969-11e4-96a0-9e3ad8d78d49.png)
![screen shot 2014-08-01 at 12 47 15](https://cloud.githubusercontent.com/assets/1426234/3777903/6cf42fe8-1969-11e4-9c9b-1d8c56428529.png)
![screen shot 2014-08-01 at 12 47 50](https://cloud.githubusercontent.com/assets/1426234/3777905/6f40ab64-1969-11e4-9267-7da7974ab7e7.png)

**Comment by stevieflow** [comment]
That looks correct to me. The error message looks a little strange. What is
the text at the start?

Sent with my thumbs...

**Comment by adriancollier** [comment]
I'm not sure, this kind of thing seems to be at the beginning of most of the error messages on the system - but success messages show correctly.

**Comment by stevieflow** [comment]
OK - Im not sure if I can help anymore here... moving to @anjesh ...

**Comment by VincentVW** [comment]
Whoops the "Got hereaa" part was caused by me, I did some ugly testing on error messages last week :). 

It now shows the the normal message "Your file could not be published in IATI Registry. Conflict (e.g. name already exists)." And after that it now shows the actual API response, could you check what the error message says now @adriancollier ? Over here the API call still returns {"name": ["Publisher name missing. Please select a publisher from the list."]}

$data in library/Ckan/Client.php  ;

string '{"name":"adrian-rsr-activities","title":"Adrian test org Activity File","author_email":"adriansakvomailintheimageabove","resources":[{"url":"http:\/\/localhost\/aidstream\/files\/xml\/adrian-rsr-activities.xml","format":"IATI-XML"}],"extras":{"filetype":"activity","country":"","activity_period-from":"","activity_period-to":"","data_updated":"2014-08-06","record_updated":"2014-08-06","activity_count":1,"verified":"no","language":"en"},"groups":["adrian-rsr"]}' (length=463)  

headers sent in library/Ckan/Client.php:

array (size=5)
  0 => string 'Date: Wed, 06 Aug 2014 07:02:51 GMT' (length=35)
  1 => string 'Accept: application/json;q=1.0, application/xml;q=0.5, _/_;q=0.0' (length=64)
  2 => string 'Accept-Charset: utf-8' (length=21)
  3 => string 'Accept-Encoding: gzip' (length=21)
  4 => string 'Authorization: c10d3ddf-b924-439c-ae01-f856e314981c' (length=51)

url used in library/Ckan/Client.php:

http://iati2.staging.ckanhosted.com/api/rest/package

I'll look further into how the $data is build up. @stevieflow Could you have a quick look at missing/wrong data in the variables above? Does the "verified":"no" mean anything bad? Or does the data need any additional publisher info than "groups":["adrian-rsr"] ?

**Comment by adriancollier** [comment]
Trying again with the above details I get:
`Your file could not be published in IATI Registry. Conflict (e.g. name already exists). Return msg from api: {"name": ["Publisher name missing. Please select a publisher from the list."]}`

**Comment by stevieflow** [comment]
@VincentVW verified status for the IATI Registry is not a mandatory 

Im not too up on the API calls - bringing in @anjesh and @bjwebb to check the call cited

**Comment by Bjwebb** [comment]
I have no experience of CKAN's data input API, I'm afraid. Maybe @anjesh has a better idea what might be going on?

**Comment by siemvaessen** [comment]
@anjesh  - any ideas on this? please advise.

**Comment by anjesh** [comment]
Looks like your aidstream instance is using old version of Registry API (1.01) instead of 1.02. Change the version to 1.02 in the config https://github.com/younginnovations/aidstream/blob/1ab81ff1f0fa10a303975f7215c0fe2d5d6d0066/application/configs/default.application.ini#L85

It should be using this https://github.com/younginnovations/aidstream/blob/1ab81ff1f0fa10a303975f7215c0fe2d5d6d0066/library/Iati/Core/Registry/MetadataGenerator/102.php instead of 101.php. Let me know if this helps.

**Comment by wendyrogers** [comment]
Hi @VincentVW et al did the above fix the problem and can this issue be closed now?
Thanks in advance

**Comment by VincentVW** [comment]
Hi @iatisupport , Anjesh his comment sounds like the fix (it indeed was using 1.01 of the Registry API) so I'll close it. We never went through to fix this and get Aidstream working on our machine.
