### ISSUE TITLE
Integration / link with youtube help videos

### ISSUE THREAD

**Issue by stevieflow** [younginnovations/aidstream-old#59]
It would be great to further integrate with the youtube support videos that @izzirbucknall has created:

https://www.youtube.com/channel/UCAVH1gcgJXElsj8ENC-bDQQ/videos

We can discuss on this thread, perhaps

**Comment by wendyrogers** [comment]
Yes would be good to point users to these especially as we have had good feedback about them and they are definitely being used. Could something be added to the main home page at www.aidstream.org?

**Comment by anjesh** [comment]
@anjhero need to put the video somewhere in the homepage - thoughts please?

**Comment by anjesh** [comment]
We will put the following text in besides the video link or button.
"Watch videos on how to use Aidstream [button to youtube channel]"

@iatisupport does that sound ok to you?

**Comment by anjesh** [comment]
Included the line on youtuve under "How to use" block.

![image](https://cloud.githubusercontent.com/assets/120488/11708025/ce71995e-9f32-11e5-8768-e0f3916e6d89.png)
