### ISSUE TITLE
label "end-actual - end-actual" in date selection dropdowns

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#6]
when adding an activity date, there's a dropdown with doubled options:
"end-actual - end-actual" etc; the double wording confuses some users

**Comment by anjesh** [comment]
Yes. It was auto-generated by the system and first "end-actual" is the code and the latter "end-actual" is the value of that code. http://iatistandard.org/codelists/activity_date_type/ somehow doesn't use numeric code. Anyways we will see if this could be made an exception.

**Comment by stevieflow** [comment]
FYI - It's likely that for IATI 2.01 these will become numeric codes: http://support.iatistandard.org/entries/41042407-Modify-code-list-activity-date-type-Language-neutral-conversion
