### ISSUE TITLE
Simplified Aidstream Outputting Boolean value as 'True' Instead of 'true'

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#62]
It looks like the simplified version of Aidstream is outputting an invalid value  for 'ascending' on the Results indicator . The data published is:

<indicator measure="1" ascending="True">

However the values allowed for ascending are 'true' or '1'.

See also related Zendesk ticket #1759

**Comment by anjesh** [comment]
This has been already fixed https://github.com/younginnovations/aidstream/commit/1ca13c47 The output XML file you have mentioned might be before the change is done. Republishing should fix the issue. Let us if you see the issue in new files.
