### ISSUE TITLE
Use protocol relative URL for external resources

### ISSUE THREAD

**Issue by iperdomo** [younginnovations/aidstream-old#63]
A safer way to include external resources. If a page is served via _https_ the user will get a warning, of including non-secure content.
- http://www.paulirish.com/2010/the-protocol-relative-url/

![https-warning](https://cloud.githubusercontent.com/assets/178474/4360908/f649fd74-427f-11e4-95ce-721cb627970a.png)

**Comment by mesaugat** [comment]
Merged.
