### ISSUE TITLE
Values To Become Mandatory For Results Baseline In V1.05

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#66]
See Zendesk ticket 1782 for more information.

Results baseline values will become mandatory at V1.05 of the IATI Standard. See also https://github.com/IATI/IATI-Websites/issues/129

**Comment by anjesh** [comment]
http://iatistandard.org/upgrades/decimal-upgrade-to-1-05/1-05-changes/ doesn't list the change.

**Comment by stevieflow** [comment]
Agree - not sure where the source of this is from @iatisupport

**Comment by wendyrogers** [comment]
Details for proposed change are on Zendesk ticket #1782/

@bjwebb is the Results baseline now mandatory in V1.05 as not explicitly mentioned in http://iatistandard.org/upgrades/decimal-upgrade-to-1-05/1-05-changes/ ?

**Comment by Bjwebb** [comment]
There has been no change to the results baseline in 1.05.

In both 1.04 (and probably before) and 1.05 the value attribute on baseline is mandatory.
Unfortunately the iatistandard.org website does not inform people of this - https://github.com/IATI/IATI-Websites/issues/129 (it does however say so in the schema, which is authoritative). Changing the website to state explicitly that baseline is required would not be a change to the standard.

**Comment by anjesh** [comment]
There are few misses in the Results form. We have fixed those and used the default UI for results, Results has diffferent UI previously. Please reopen this issue if you find any issues with Results.
