### ISSUE TITLE
add user-defined country to list

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#7]
there's no option to add a user-defined country (which is possible in
ISO-3166, code QM..QZ, XA..XZ, ZZ); for instance: Kosovo (several
institutions use XK for that)

**Comment by wendyrogers** [comment]
See also proposed changes to IATI Standard http://support.iatistandard.org/entries/49470037-Extending-Country-Codelist-To-Include-Kosovo

**Comment by rolfkleef** [comment]
I've added a comment there: making a clearer reference to the ISO-3166 country list may help?

**Comment by stevieflow** [comment]
Putting into 1.04 milestone , due to `location` changes (although this isnt `location` specific

**Comment by stevieflow** [comment]
I think it worth considering this discussion first of all: http://support.iatistandard.org/entries/49470037-Extending-Country-Codelist-To-Include-Kosovo

**Comment by wendyrogers** [comment]
It has now been agree to add 'XK' for Kosovo to the IATI non embedded codelist for countries (see https://groups.google.com/forum/#!topic/iati-technical/XaPyCAawzi8). Therefore can we now add 'XK' to the drop down list of countries in Aidstream and update the associate help message?

**Comment by mesaugat** [comment]
`XK` - Kosovo has been added to the list of countries and the associated help message is also fixed. Thank you.
