### ISSUE TITLE
Activity element "Other identifier" not clear

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#73]
When entering the "Other identifier" element in an activity record, the help texts are not quite clear on what type of identifier is meant. The Standard says it's a "non-IATI identifier", the fields in AidStream suggest to the casual user an IATI identifier is expected.

Might be good to update the help text to be closer to the SSOT reference text?

**Comment by stevieflow** [comment]
Good spot @rolfkleef - this inconsistency was picked up in the SSOT when we moved to 1.04

It's worth noting that `other-identifier` is subject to significant change in 2.01: http://support.iatistandard.org/entries/52824355-Version-2-01-Iteration-3-9-Organisation-and-Activity-Identifiers

**Comment by anjesh** [comment]
Got it. Will update the help text for now.
