### ISSUE TITLE
Include DAC-3 sector list

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#76]
Currently, it's possible to add DAC-5 sector codes, but for NGOs that do not work with DAC sector codes at all (but with a different taxonomy) it would be a lot easier to provide DAC-3 sector codes, and still provide reasonable detail for DAC sector-based reporting.

**Comment by wendyrogers** [comment]
Just to add that we are also planning to enhance our guidance to recommend to Non-DAC IATI publishers that they always include a 3 digit DAC code if possible. This therefore would appear to increase the priority of this issue

**Comment by wendyrogers** [comment]
The Aidstream development team have suggested that they could change the interface for adding DAC sector codes so that the user can first select the 3 digit code and then if they choose to select the 5 digit code from a much reduced drop down list. This seems a very good approach

**Comment by rolfkleef** [comment]
this sounds perfect!

**Comment by anjesh** [comment]
The 3-digit sector vocab is now listed in the vocab, however it doesn't yet list the 3-digit sectors but shows the text box. Need to address this. 

![image](https://cloud.githubusercontent.com/assets/120488/10976028/ec4fe4bc-8411-11e5-86a7-5dd093a5e8f4.png)

**Comment by anjesh** [comment]
3 digit sector codes are now listed and gets reflected in the XML as well.

![image](https://cloud.githubusercontent.com/assets/120488/11416072/5c694650-9432-11e5-98a3-89513341dd67.png)

Please verify and close the ticket.

**Comment by rolfkleef** [comment]
Thanks!

In the meantime the Dutch MFA has made 5-digit sector codes a requirement for their grantees... :-/
