### ISSUE TITLE
Formatting the XML files

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#83]
As a user, I want to download a well-formatted XML file, so that it is easier to interpret in my text editor

---

The IATI activities file may be valid XML, but basically is a long string, mostly on a single line of text. This makes it hard to do anything with it from a regular user's perspective.

It would be helpful to for instance run "xmllint --format" on the file (this is what I usually do); and perhaps to provide a syntax-coloured preview with line numbers through something like the SyntaxHighlighter: http://alexgorbatchev.com/SyntaxHighlighter/manual/installation.html (I suggested that for the CSV2IATI conversion tool too: https://github.com/IATI/CSV2IATI/issues/202)

**Comment by stevieflow** [comment]
+1

I've also noticed that in the (rare) occassions that an AidStream file fails schema validation - the current formatting makes it difficult to pinpoint the relevant issue/line/element
