### ISSUE TITLE
values as decimal

### ISSUE THREAD

**Issue by stevieflow** [younginnovations/aidstream-old#84]
Take a look at this file:

Validation report:

http://validator.iatistandard.org/?perm=www.aidstream.org_files_xml_hfhgb-br.xml_1414579862

2   Error 1824  Element 'coordinates', attribute 'latitude': '-08° 03' 14''' is not a valid value of the atomic type 'xs:decimal'.
2   Error 1824  Element 'coordinates', attribute 'longitude': '-34° 52' 52''' is not a valid value of the atomic type 'xs:decimal'.
2   Error 1824  Element 'capital-spend', attribute 'percentage': '1%' is not a valid value of the atomic type 'xs:decimal'.

Perhaps AidStream should/could  be rendering/correcting such input as users enter values?

**Comment by anjesh** [comment]
The location now only allows decimals though capital-spend takes string. Need to fix. 

![image](https://cloud.githubusercontent.com/assets/120488/10976116/58e5e75c-8412-11e5-9b65-5c016ecb243f.png)

This file https://www.aidstream.org/files/xml/hfhgb-br.xml still has problem and needs to be edited and republished to fix the validation error.

**Comment by anjesh** [comment]
Capital spend now takes only numeric.

![image](https://cloud.githubusercontent.com/assets/120488/11416099/93c64d3c-9432-11e5-9179-1b5ccf208afa.png)
