### ISSUE TITLE
documentlink with spaces in file name

### ISSUE THREAD

**Issue by stevieflow** [younginnovations/aidstream-old#85]
If a user uploads a document that has spaces in the filename, they can insert the file in as a document-link URL, but AidStream then doesnt recognise this as a URL:

![index](https://cloud.githubusercontent.com/assets/1209944/4831688/7ef4a632-5f96-11e4-947d-bb070c0877c9.JPG)

AidStream should render any such file names into URLs that have such spaces (and possibly characters) escaped

**Comment by geshan** [comment]
good idea.

**Comment by mesaugat** [comment]
This is done to prevent users from entering two or more links on a single field. For example: `http://aidstream.org, http://example.com` would be valid, which was stated back in #65 

We can encode the file name into URLs for documents uploaded to AidStream. But for other URL's with spaces or invalid characters in between it could be difficult. This will also make the above example a valid URL which was the previous case. Any ideas ?

**Comment by stevieflow** [comment]
Thanks - I can see what you mean.

For files that are uploaded via Aidstream, could they be encoded into valid URLs (as in URLs without spaces)?

In terms of users who then add URLs that include spaces, then perhaps this rests in a guidance / tooltip to alert them?  And / or - I guess AidStream could escape spaces in URLs once they are submitted by the user -  but this might need more logic building in.  Perhaps guidance is the best solution in this case.

**Comment by mesaugat** [comment]
Yes, those files which are uploaded to AidStream can be encoded into valid URL's without spaces. Escaping spaces is not right. For other invalid URL's providing guidance seems to be right.

**Comment by stevieflow** [comment]
Yes, sorry - my typo for suggesting "escape spaces"

**Comment by mesaugat** [comment]
Fixed with current update (v1.3.1). However, spaces are not allowed in URL and a error message stating that will be shown if the user inserts an invalid URL with spaces or other invalid characters.
