### ISSUE TITLE
Copy projet bugs results 

### ISSUE THREAD

**Issue by Jaspermid** [younginnovations/aidstream-old#86]
Hi Guys, 

I have copied a project in Aidstream but this seems to have bugged my results. All the results in my original project are now almost empty (except for the type), the results in the copied project is working. have heard this bug from other NGO's as well. Hope you can help out.

Cheers,

Jasper

**Comment by anjesh** [comment]
I checked and the duplicating the activity doesn't lose the results data now. Do verify.

**Comment by anjesh** [comment]
Closing this. Please reopen if there's anything.
