### ISSUE TITLE
Lost IATI data while copying

### ISSUE THREAD

**Issue by Jaspermid** [younginnovations/aidstream-old#88]
After copying a project and deleting the old project I have lost some information in te Partos_nl midstream file. 
1. I copied a project.
2. The results were now missing in the original project while they were present in the copied project
3. Deleted the original but did not notice all the transactions are gone. 

Is there any way to retrieve this data? In any case copying a project seems to create some issues. 

Linked to issue #86

**Comment by mesaugat** [comment]
Yes, the results disappear from the original when copying. This seems to be a bug. However, transactions are not copied. You have to manually add transactions to the duplicated activity. Deleted activity cannot be retrieved.

**Comment by wendyrogers** [comment]
There is also a problem with the copy with the Sector and Budget fields. Sector disappeared from the source project and the only the value field of the budget element was copied to the new project and all the budget details disappeared from the source project

**Comment by rolfkleef** [comment]
I'd like to raise the priority of this please. We've had this issue happen to users again: sector information lost, budget information lost...

**Comment by anjesh** [comment]
Fixed and updated in the live.
