### ISSUE TITLE
Changing Org ID in Settings does not affect Organisation file

### ISSUE THREAD

**Issue by stevieflow** [younginnovations/aidstream-old#89]
This file: http://aidstream.org/files/xml/apt-org.xml - the Org ID has an extra whitespace.  In the account settings, I've edited the Org ID (twice), which has in turn edited the activity files.  This does not apply to the Org file.  There is also no way to edit the Org ID in this file.

**Comment by stevieflow** [comment]
Update

Changing the identifier in Settings does change the data in aidstream, but this is not pushed through to the live Org file

**Comment by anjesh** [comment]
We have fixed this in V201.

**Comment by wendyrogers** [comment]
@stevieflow could you test this one just to check that this has been fixed correctly. Thanks

**Comment by anjesh** [comment]
Closing this. Please reopen if there's any issue with this.
