### ISSUE TITLE
adding a Location item is overwhelming and too complicated

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#9]
it's hard to grasp all the different parts of the form and how they relate

probably the "flow" for adding a location should be (re)considered, maybe creating a wizard or so? "pointing on a map" with a good search as starting point?

**Comment by stevieflow** [comment]
Putting into 1.04 milestone , due to `location` changes

**Comment by anjesh** [comment]
Duplicate of https://github.com/younginnovations/aidstream/issues/48
