### ISSUE TITLE
Strip out trailing / leading whitespace from Org identifiers 

### ISSUE THREAD

**Issue by stevieflow** [younginnovations/aidstream-old#90]
I've noticed a few orgs that have created an Org ID "12345 "

The extra space seems to be carried through to the data.  It would be good for AidStream to clean this on entry, and remove such spaces

**Comment by anjesh** [comment]
This one should be fixed in #42. can you give specific examples of where you find this?

**Comment by stevieflow** [comment]
OK thanks - have tested the test account and can see that the spaces are removed.  I would guess that those accounts that still have identifiers with extra whitespace, would have to republish?  But anyway, this is fine
