### ISSUE TITLE
Number of activities in the dashboard under IATI Registry Block is different from the actual published

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream-old#91]
In the attached image, we can see that activities published is 15 whereas under IATI registry shows 18. The activities number seems to be coming from all the IATI XML files which are present but not necessarily published. There are 8 files published and listed in IATI Registry whereas there are 10 files in the AidStream. Probably that's giving the wrong activities count. 

![screen shot 2014-12-04 at 3 38 40 pm](https://cloud.githubusercontent.com/assets/120488/5296475/65356a9a-7bcc-11e4-8884-4a9b4342c706.png)

**Comment by stevieflow** [comment]
Hi @anjesh - can you say which organisation this is (or the URL to their Refistry page?)?

**Comment by anjesh** [comment]
It's the for the Pontis Foundation http://iatiregistry.org/publisher/pontis

**Comment by mesaugat** [comment]
Fixed.
