### ISSUE TITLE
Check for duplicate identifier

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream-old#92]
As a user I want to receive a warning message when I enter an already existing activity identifier for a new activity.

---

It's easy to accidently enter another activity with the same identifier, a warning that an identifier is already present can prevent duplicate entry or mistakes. For me there's no need to prevent a user from doing it, but two things will help a user detect and resolve this:
- a warning message upon saving such an activity
- perhaps a different color in the list of activities with a warning underneath "this identifier occurs multiple times"

**Comment by mesaugat** [comment]
This is the same issue as #100 and has been resolved now.
